### ISSUE TITLE
Error calculating relaxation rates

### ISSUE THREAD

**Issue by makochmanichf** [LeonardoESousa/NEMO#4]
Dear Leonardo,

I'm trying to learn to use NEMO in order to calculate intersystem crossing rates. I carried out some test calculations for 6-thioguanine, a photosensitizer that is known to undergo rapid singlet --> triplet intersystem crossing.

I was able to follow the tutorial up to the "Emission Spectra and Rates" section. I optimized the geometry of my molecule in state S1 at the TDDFT level (wB97XD/def2-SVP), and I calculated the normal modes. I then generated an ensemble of 500 molecular geometries, and performed single-point calculations for all of them. When I tried to calculate the ISC rate, I got some nonsensical results:

#Epsilon: 2.380 nr: 1.497
Transition Rate(s^-1) Error(s^-1) Prob(%) AvgDE+L(eV) AvgSOC(meV) AvgSigma(eV) AvgConc(%)
    S1->S0   2.55e+12    2.50e+12    98.2   -7361.658         nan        0.048        0.2
    S1~>T1   3.78e-30    3.78e-30     0.0      -0.393      13.457        0.029        0.2
    S1~>T2   3.80e-11    3.58e-11     0.0      -0.315       3.005        0.033        0.2
    S1~>T3   4.65e+10    2.40e+10     1.8      -0.003       7.370        0.027        0.7
    S1~>T4   2.77e+08    2.75e+08     0.0       0.024       1.194        0.026        0.2
    S1~>T5   1.27e-66    1.27e-66     0.0       0.541       2.736        0.029        0.2
    S1~>T6   0.00e-99    0.00e-99     0.0       0.917      19.778        0.029      100.0
    S1~>T7   0.00e-99    0.00e-99     0.0      41.531       3.468        0.028        0.0
    S1~>T8   0.00e-99    0.00e-99     0.0      41.748       3.527        0.028        0.0
    S1~>T9   0.00e-99    0.00e-99     0.0      41.913       3.534        0.028        0.0
   S1~>T10   0.00e-99    0.00e-99     0.0      42.039       4.532        0.028        0.0
   
The S1->S0 emission rate seems far too high. The  S1-S0, S1-T7, S1-T8, S1-T9, and S1-T10 average energy gaps are clearly wrong - the S1-S0 energy gap is actually around 2 eV. The program did not throw any error messages. 

Can you please help me figure out what went wrong here?

I am using NEMO Version: 1.2.0 and Q-Chem 5.0, but I also have access to some newer versions of Q-Chem. I'm attaching the relevant input and output files. 

With best regards,

Michał Kochman

[6thioguanine_data.zip](https://github.com/user-attachments/files/17014816/6thioguanine_data.zip)

**Comment by LeonardoESousa** [comment]
Hello Michal, thanks for reaching out. It seems that the issue results from some weird numbers appearing in the QChem calculations. For instance, in your Geometry 1, the state-specific solvation block reads as follows:

> 
Relaxed   singlet excited state    3:
   Total  1st-order corrected excitation energy  =  22.702243 eV
   1st-order SS-PCM corrected excitation energy  =  22.711936 eV
   1st-order LR-PCM corrected excitation energy  =   2.782128 eV
   0th-order exctition energy                    =   2.791820 eV
   SS-PCM correction                             =  19.920116 eV
   LR-PCM correction                             =  -0.009692 eV
   Charge-separation penalty                     =  27.211384 eV
   Dipole Mom. (Debye):    3.3568 X   -2.7461 Y    4.9945 Z
   Strength |mu - mu_0| (Debye):   3.8975
>
   
  You can see that there is a huge non-physical SS-PCM correction (~20 eV). 

I ran the same input on QChem 6.0 and got the following:

>
 Relaxed   singlet excited state    3:
   0th-order excitation energy              =   2.791781 eV
   1st-order ptSS-PCM correction            =  -0.087307 eV
   1st-order ptLR-PCM correction            =  -0.009650 eV
   ptSS-PCM 1st-order corrected exc. energy =   2.704474 eV
   ptLR-PCM 1st-order corrected exc. energy =   2.782130 eV
   Total 1st-order (ptSS+ptLR)  exc. energy =   2.694824 eV
   Dipole Mom. (Debye):    3.3547 X   -2.7476 Y    4.9966 Z
   Strength |mu - mu_0| (Debye):   3.8973
>

Note that the 0th order energy is basically the same in both cases, but the SS correction is now at -0.087307 eV, a much more reasonable value. Since you have access to more recent QChem versions, I suggest you try running the calculations again with one of those. 

On another note, once your calculations are done, consider using the [visualization program](https://github.com/LeonardoESousa/nemoview) to see results in more detail. 

Let me know if you have more questions.

**Comment by makochmanichf** [comment]
Dear Leonardo,

Thank you for your prompt reply! It didn't occur to me the problem could be due to the solvent model. I re-ran the TDDFT calculations with Q-Chem 5.3, and the excitation energies are now okay. That definitely does look like a bug in Q-Chem 5.0.

The rate constants I'm getting now are much more reasonable, see below.

With best regards,

Michał



#Epsilon: 2.380 nr: 1.497
Transition Rate(s^-1) Error(s^-1) Prob(%) AvgDE+L(eV) AvgSOC(meV) AvgSigma(eV) AvgConc(%)
    S1->S0   2.97e+05    0.32e+05   100.0       2.725         nan        0.049       46.0
    S1~>T1   4.26e-21    4.26e-21     0.0      -0.516      20.058        0.028      100.0
    S1~>T2   5.80e-03    4.15e-03     0.0      -0.299       2.724        0.031      100.0
    S1~>T3   4.11e-24    3.24e-24     0.0       1.132       5.746        0.027      100.0
    S1~>T4   0.00e-99    0.00e-99     0.0       1.483       5.424        0.027      100.0
    S1~>T5   0.00e-99    0.00e-99     0.0       2.092       6.021        0.028        0.0
    S1~>T6   0.00e-99    0.00e-99     0.0       2.396       3.270        0.028        0.0
    S1~>T7   0.00e-99    0.00e-99     0.0       2.664       3.130        0.028        0.0
    S1~>T8   0.00e-99    0.00e-99     0.0       2.877       3.322        0.029        0.0
    S1~>T9   0.00e-99    0.00e-99     0.0       3.033       3.744        0.028        0.0
   S1~>T10   0.00e-99    0.00e-99     0.0       3.158       4.496        0.027        0.0
==> rates_S2_.lx <==
#Epsilon: 2.380 nr: 1.497
Transition Rate(s^-1) Error(s^-1) Prob(%) AvgDE+L(eV) AvgSOC(meV) AvgSigma(eV) AvgConc(%)
    S2->S0   4.81e+08    0.12e+08     1.5       3.773         nan        0.048       94.3
    S2~>T1   0.00e-99    0.00e-99     0.0      -1.467       2.607        0.028        0.0
    S2~>T2   0.00e-99    0.00e-99     0.0      -1.250      17.709        0.031      100.0
    S2~>T3   1.40e+10    0.59e+10    44.5       0.181       1.307        0.027      100.0
    S2~>T4   1.70e+10    1.67e+10    54.0       0.531       1.399        0.027      100.0
    S2~>T5   4.78e-45    4.78e-45     0.0       1.140       4.522        0.028      100.0
    S2~>T6   0.00e-99    0.00e-99     0.0       1.445       2.582        0.028      100.0
    S2~>T7   0.00e-99    0.00e-99     0.0       1.713       2.316        0.028      100.0
    S2~>T8   0.00e-99    0.00e-99     0.0       1.925       3.066        0.029        0.0
    S2~>T9   0.00e-99    0.00e-99     0.0       2.081       3.497        0.028        0.0
   S2~>T10   0.00e-99    0.00e-99     0.0       2.206       3.691        0.027        0.0

**Comment by LeonardoESousa** [comment]
Good to know it's working! I'm closing the issue then.
